apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: zpod
  namespace: default
spec:
  selector:
    matchLabels:
      app: zpod
  replicas: 1
  template:
    metadata:
      namespace: default
      labels:
        app: zpod
    spec:
      serviceAccountName: beak-service-role
      containers:
      - name: zpod
        image: zconger/zpod
        command: ["sleep"]
        args: ["86400"]
